name: main_workflow
on:
  push:
    branches:
      - nodejs_environment_job
jobs:
  job1:
      name: linter-execution
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setting node version
          uses: actions/setup-node@v2
        - name: Linter execution
          uses: github/super-linter@v3.17.0
          env:
            DEFAULT_BRANCH: nodejs_linter_job
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LINTER_RULES_PATH: /linters
            JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
            VALIDATE_JAVASCRIPT_ES: true
  job2:
      name: test-execution
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run jest tests
          run: |
            npm install jest
            npm test
  job3:
      name: environment_test_execution
      runs-on: ubuntu-latest
      steps:
        - name: Mostrar cadena
          uses: adeloyedeji/github-actions-hello@v1.0 
          with: 
            who-to-greet: '${{ env.DESTINATION_PERSON }}'
          env:
            DESTINATION_PERSON: '2DAW'
    
    