name: main_workflow
on:
  push:
    branches:
      - nodejs_jest_job
jobs:
  job1:
      name: linter-execution
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Linter execution
          uses: github/super-linter@v3.17.0
          env:
            DEFAULT_BRANCH: nodejs_linter_job
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LINTER_RULES_PATH: .github/linters
            JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
            VALIDATE_JAVASCRIPT_ES: true
  job2:
      name: test-execution
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install jest
          run: npm install --save-dev jest
        - name: Run jest tests
          run: npm test
    
    